// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
export const webSocketBindingSchemaDocumentsV1 = Object.freeze([
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:codes:binding-rejection-code",
    "title": "WebSocketBindingRejectionCode",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketBindingRejectionCode",
      "kind": "code",
      "mechanics": "Defines the binding-rejection-code value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "Closed private WebSocket rejection classification.",
    "type": "string",
    "enum": [
      "TEXT_MESSAGE",
      "INVALID_TEXT_UTF8",
      "PACKET_TOO_LARGE",
      "MALFORMED_FRAMING",
      "RECEIVE_OVERFLOW"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:common:subprotocol-token",
    "title": "WebSocketSubprotocolToken",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketSubprotocolToken",
      "kind": "scalar",
      "mechanics": "Defines the subprotocol-token value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "Exact RFC 6455 subprotocol token selecting the AGP v1 binary binding.",
    "const": "agp.v1"
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:compression",
    "title": "WebSocketCompressionConfig",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketCompressionConfig",
      "kind": "configuration",
      "mechanics": "Defines the compression value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "Closed RFC 7692 compression configuration.",
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "mode": {
            "const": "disabled",
            "description": "No WebSocket data-message compression."
          }
        },
        "required": [
          "mode"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "mode": {
            "const": "permessage-deflate",
            "description": "Explicit bounded RFC 7692 compression."
          },
          "maxCompressedBytes": {
            "type": "integer",
            "description": "Maximum compressed carrier-message bytes.",
            "minimum": 1,
            "maximum": 9007199254740991
          },
          "noContextTakeover": {
            "const": true,
            "description": "Both directions disable context takeover."
          }
        },
        "required": [
          "mode",
          "maxCompressedBytes",
          "noContextTakeover"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:listener",
    "title": "WebSocketListenerConfigData",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketListenerConfigData",
      "kind": "configuration",
      "mechanics": "Defines the listener value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "One WebSocket listener capability binding.",
    "type": "object",
    "properties": {
      "transportRef": {
        "$ref": "urn:agp:schema:v1:transport:common:transport-ref",
        "description": "Application-local logical acquisition reference."
      },
      "url": {
        "type": "string",
        "description": "Bound trusted-development ws: locator.",
        "minLength": 1,
        "maxLength": 2048,
        "pattern": "^[^\\u0000-\\u001F\\u007F]+$"
      },
      "compression": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:compression",
        "description": "Carrier compression policy."
      },
      "liveness": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:liveness",
        "description": "Optional carrier-private liveness policy."
      },
      "security": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:security",
        "description": "Exact certified security profile."
      },
      "displayAddress": {
        "type": "string",
        "description": "Optional sanitized operator display evidence.",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[^\\u0000-\\u001F\\u007F]+$"
      }
    },
    "required": [
      "transportRef",
      "url",
      "compression",
      "security"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:liveness",
    "title": "WebSocketLivenessConfigData",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketLivenessConfigData",
      "kind": "configuration",
      "mechanics": "Defines the liveness value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "Finite carrier-private Ping/Pong liveness settings.",
    "type": "object",
    "properties": {
      "pingIntervalMs": {
        "type": "integer",
        "description": "Interval between adapter Ping probes.",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "pongTimeoutMs": {
        "type": "integer",
        "description": "Deadline for the matching Pong.",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    },
    "required": [
      "pingIntervalMs",
      "pongTimeoutMs"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:security",
    "title": "WebSocketSecurityConfigData",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketSecurityConfigData",
      "kind": "configuration",
      "mechanics": "Defines the security value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "Certified trusted-development security declaration.",
    "type": "object",
    "properties": {
      "mode": {
        "const": "trusted-development",
        "description": "Explicit unauthenticated cleartext development profile."
      }
    },
    "required": [
      "mode"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:target",
    "title": "WebSocketTargetConfigData",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketTargetConfigData",
      "kind": "configuration",
      "mechanics": "Defines the target value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": []
    },
    "description": "One WebSocket outbound target capability binding.",
    "type": "object",
    "properties": {
      "transportRef": {
        "$ref": "urn:agp:schema:v1:transport:common:transport-ref",
        "description": "Application-local logical acquisition reference."
      },
      "url": {
        "type": "string",
        "description": "Bound trusted-development ws: locator.",
        "minLength": 1,
        "maxLength": 2048,
        "pattern": "^[^\\u0000-\\u001F\\u007F]+$"
      },
      "compression": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:compression",
        "description": "Carrier compression policy."
      },
      "liveness": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:liveness",
        "description": "Optional carrier-private liveness policy."
      },
      "security": {
        "$ref": "urn:agp:schema:v1:binding-websocket:configuration:security",
        "description": "Exact certified security profile."
      }
    },
    "required": [
      "transportRef",
      "url",
      "compression",
      "security"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:configuration:transport",
    "title": "WebSocketTransportConfigData",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketTransportConfigData",
      "kind": "configuration",
      "mechanics": "Defines the transport value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": [
        "WEBSOCKET-REFERENCE-UNIQUENESS-1"
      ]
    },
    "description": "Complete resolver input for one certified WebSocket adapter.",
    "type": "object",
    "properties": {
      "listeners": {
        "type": "array",
        "description": "Listener capability bindings.",
        "items": {
          "$ref": "urn:agp:schema:v1:binding-websocket:configuration:listener"
        },
        "maxItems": 4096
      },
      "targets": {
        "type": "array",
        "description": "Outbound target capability bindings.",
        "items": {
          "$ref": "urn:agp:schema:v1:binding-websocket:configuration:target"
        },
        "maxItems": 4096
      }
    },
    "required": [
      "listeners",
      "targets"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:binding-websocket:contracts:close-mapping",
    "title": "WebSocketCloseMapping",
    "x-agp": {
      "owner": "@agp/binding-websocket",
      "typescript": "WebSocketCloseMapping",
      "kind": "contract",
      "mechanics": "Defines the close-mapping value owned by the WebSocket binding.",
      "rationale": "Carrier-specific configuration and mapping remain outside the neutral kernel.",
      "consequence": "Divergence makes WebSocket behavior ambiguous or leaks carrier authority.",
      "semanticRules": [
        "WEBSOCKET-PACKET-BINDING-1"
      ]
    },
    "description": "Sovereign projection from binding condition to empty-reason RFC 6455 close action.",
    "type": "object",
    "properties": {
      "condition": {
        "type": "string",
        "enum": [
          "local-close",
          "malformed-framing",
          "text-message",
          "invalid-text-utf8",
          "packet-too-large",
          "receive-overflow",
          "adapter-fault"
        ],
        "description": "Closed binding-owned condition."
      },
      "closeCode": {
        "type": "integer",
        "enum": [
          1000,
          1002,
          1003,
          1007,
          1009,
          1011
        ],
        "description": "RFC 6455 close status selected by the binding."
      },
      "reason": {
        "const": "",
        "description": "Binding-initiated close reasons are always empty."
      }
    },
    "required": [
      "condition",
      "closeCode",
      "reason"
    ],
    "additionalProperties": false
  }
]) as readonly Readonly<Record<string, unknown>>[];
