// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
import type { TransportRef } from "@agp/transport";

export type WebSocketSubprotocolToken = "agp.v1";
export type WebSocketBindingRejectionCode =
  | "TEXT_MESSAGE"
  | "INVALID_TEXT_UTF8"
  | "PACKET_TOO_LARGE"
  | "MALFORMED_FRAMING"
  | "RECEIVE_OVERFLOW";
export interface WebSocketSecurityConfigData {
  readonly mode: "trusted-development";
}
export type WebSocketCompressionConfig =
  | Readonly<{ mode: "disabled" }>
  | Readonly<{
      mode: "permessage-deflate";
      maxCompressedBytes: number;
      noContextTakeover: true;
    }>;
export interface WebSocketLivenessConfigData {
  readonly pingIntervalMs: number;
  readonly pongTimeoutMs: number;
}
export interface WebSocketListenerConfigData {
  readonly transportRef: TransportRef;
  readonly url: string;
  readonly displayAddress?: string;
  readonly compression: WebSocketCompressionConfig;
  readonly liveness?: WebSocketLivenessConfigData;
  readonly security: WebSocketSecurityConfigData;
}
export interface WebSocketTargetConfigData {
  readonly transportRef: TransportRef;
  readonly url: string;
  readonly compression: WebSocketCompressionConfig;
  readonly liveness?: WebSocketLivenessConfigData;
  readonly security: WebSocketSecurityConfigData;
}
export interface WebSocketTransportConfigData {
  readonly listeners: readonly WebSocketListenerConfigData[];
  readonly targets: readonly WebSocketTargetConfigData[];
}
export interface WebSocketCloseMapping {
  readonly condition:
    | "local-close"
    | "malformed-framing"
    | "text-message"
    | "invalid-text-utf8"
    | "packet-too-large"
    | "receive-overflow"
    | "adapter-fault";
  readonly closeCode: 1000 | 1002 | 1003 | 1007 | 1009 | 1011;
  readonly reason: "";
}
