// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
export const loopbackSchemaDocumentsV1 = Object.freeze([
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:codes:counter-key",
    "title": "AGP Loopback counter-key",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "CounterKey",
      "kind": "code",
      "mechanics": "Sovereign counter-key data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Closed Loopback counter catalog key.",
    "type": "string",
    "enum": [
      "connectionsAccepted",
      "connectionsRejected",
      "packetsAcceptedLeftToRight",
      "bytesAcceptedLeftToRight",
      "packetsAcceptedRightToLeft",
      "bytesAcceptedRightToLeft",
      "backpressureActivations",
      "gracefulChannelCloses",
      "forcedChannelAborts",
      "adapterInvariantFaults"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:codes:fabric-failure-code",
    "title": "AGP Loopback fabric-failure-code",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "FabricFailureCode",
      "kind": "code",
      "mechanics": "Sovereign fabric-failure-code data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Closed terminal failure class for one fabric.",
    "type": "string",
    "enum": [
      "MONOTONIC_DOMAIN_EXHAUSTED",
      "ADAPTER_FAULT"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:codes:monotonic-domain",
    "title": "AGP Loopback monotonic-domain",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "MonotonicDomain",
      "kind": "code",
      "mechanics": "Sovereign monotonic-domain data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Finite ordering domain that caused fabric failure.",
    "type": "string",
    "enum": [
      "revision",
      "counter",
      "arbitration-sequence"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:common:counter-value",
    "title": "AGP Loopback counter-value",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "CounterValue",
      "kind": "common",
      "mechanics": "Sovereign counter-value data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-MONOTONIC-EXHAUSTION-1"
      ]
    },
    "description": "Canonical unsigned-64 decimal counter value.",
    "type": "string",
    "pattern": "^(0|[1-9][0-9]{0,19})$",
    "maxLength": 20
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:common:fabric-id",
    "title": "AGP Loopback fabric-id",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "FabricId",
      "kind": "common",
      "mechanics": "Sovereign fabric-id data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Bounded display identity of one explicit fabric object.",
    "type": "string",
    "pattern": "^[a-z0-9][a-z0-9._-]{0,62}$"
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:common:fabric-revision",
    "title": "AGP Loopback fabric-revision",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "FabricRevision",
      "kind": "common",
      "mechanics": "Sovereign fabric-revision data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-MONOTONIC-EXHAUSTION-1"
      ]
    },
    "description": "Canonical unsigned-64 decimal fabric revision.",
    "type": "string",
    "pattern": "^(0|[1-9][0-9]{0,19})$",
    "maxLength": 20
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:common:loopback-address",
    "title": "AGP Loopback loopback-address",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "LoopbackAddress",
      "kind": "common",
      "mechanics": "Sovereign loopback-address data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Exact slash-separated listener address inside one fabric.",
    "type": "string",
    "pattern": "^[a-z0-9][a-z0-9._-]{0,62}(?:/[a-z0-9][a-z0-9._-]{0,62})*$",
    "maxLength": 253
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:common:transport-name",
    "title": "AGP Loopback transport-name",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "TransportName",
      "kind": "common",
      "mechanics": "Sovereign transport-name data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "description": "Fabric-issued name of one scoped transport capability.",
    "type": "string",
    "pattern": "^[a-z0-9][a-z0-9._-]{0,62}$"
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:configuration:fabric",
    "title": "AGP Loopback fabric",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "Fabric",
      "kind": "configuration",
      "mechanics": "Sovereign fabric data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-EXPLICIT-FABRIC-1"
      ]
    },
    "type": "object",
    "properties": {
      "fabricId": {
        "description": "Display identity checked against bound listener and target data.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
      },
      "limits": {
        "description": "Finite production resource ceilings.",
        "$ref": "urn:agp:schema:v1:transport-loopback:configuration:limits"
      }
    },
    "required": [
      "fabricId",
      "limits"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:configuration:limits",
    "title": "AGP Loopback limits",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "Limits",
      "kind": "configuration",
      "mechanics": "Sovereign limits data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-EXPLICIT-FABRIC-1"
      ]
    },
    "type": "object",
    "properties": {
      "maxTransports": {
        "description": "Hard fabric ceiling for maxTransports.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxListeners": {
        "description": "Hard fabric ceiling for maxListeners.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxPendingAcquisitions": {
        "description": "Hard fabric ceiling for maxPendingAcquisitions.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxActiveChannels": {
        "description": "Hard fabric ceiling for maxActiveChannels.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxPacketBytes": {
        "description": "Hard fabric ceiling for maxPacketBytes.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxBufferedPacketsPerChannel": {
        "description": "Hard fabric ceiling for maxBufferedPacketsPerChannel.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxBufferedBytesPerChannel": {
        "description": "Hard fabric ceiling for maxBufferedBytesPerChannel.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxQueuedPacketsTotal": {
        "description": "Hard fabric ceiling for maxQueuedPacketsTotal.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxQueuedBytesTotal": {
        "description": "Hard fabric ceiling for maxQueuedBytesTotal.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "maxPendingSendBytesTotal": {
        "description": "Hard fabric ceiling for maxPendingSendBytesTotal.",
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    },
    "required": [
      "maxTransports",
      "maxListeners",
      "maxPendingAcquisitions",
      "maxActiveChannels",
      "maxPacketBytes",
      "maxBufferedPacketsPerChannel",
      "maxBufferedBytesPerChannel",
      "maxQueuedPacketsTotal",
      "maxQueuedBytesTotal",
      "maxPendingSendBytesTotal"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:configuration:listener",
    "title": "AGP Loopback listener",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "Listener",
      "kind": "configuration",
      "mechanics": "Sovereign listener data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-EXPLICIT-FABRIC-1"
      ]
    },
    "type": "object",
    "properties": {
      "fabricId": {
        "description": "Display identity that must equal the exact owning fabric.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
      },
      "address": {
        "description": "Exact listener address inside the owning fabric.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:loopback-address"
      }
    },
    "required": [
      "fabricId",
      "address"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:configuration:target",
    "title": "AGP Loopback target",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "Target",
      "kind": "configuration",
      "mechanics": "Sovereign target data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-EXPLICIT-FABRIC-1"
      ]
    },
    "type": "object",
    "properties": {
      "fabricId": {
        "description": "Display identity that must equal the exact owning fabric.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
      },
      "address": {
        "description": "Exact listener address inside the owning fabric.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:loopback-address"
      }
    },
    "required": [
      "fabricId",
      "address"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:configuration:transport",
    "title": "AGP Loopback transport",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "Transport",
      "kind": "configuration",
      "mechanics": "Sovereign transport data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-EXPLICIT-FABRIC-1"
      ]
    },
    "type": "object",
    "properties": {
      "transportName": {
        "description": "Unique name reserved for this fabric lifetime.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
      },
      "capabilities": {
        "description": "Fixed acquisition kinds this scoped transport may bind.",
        "type": "object",
        "properties": {
          "listen": {
            "description": "Whether listener capabilities may be bound.",
            "type": "boolean"
          },
          "connect": {
            "description": "Whether target capabilities may be bound.",
            "type": "boolean"
          }
        },
        "required": [
          "listen",
          "connect"
        ],
        "additionalProperties": false
      }
    },
    "required": [
      "transportName",
      "capabilities"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot",
    "title": "AGP Loopback channel-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "ChannelSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign channel-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-SNAPSHOT-RETENTION-1"
      ]
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "channelId": {
            "description": "Opaque bounded fabric-local channel identity.",
            "type": "string",
            "pattern": "^channel-[0-9a-f]{16}$"
          },
          "leftTransport": {
            "description": "Connecting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "rightTransport": {
            "description": "Accepting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "queuedPacketsLeft": {
            "description": "Packets queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesLeft": {
            "description": "Bytes queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedPacketsRight": {
            "description": "Packets queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesRight": {
            "description": "Bytes queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Both endpoints are open.",
            "const": "Open"
          }
        },
        "required": [
          "channelId",
          "leftTransport",
          "rightTransport",
          "queuedPacketsLeft",
          "queuedBytesLeft",
          "queuedPacketsRight",
          "queuedBytesRight",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "channelId": {
            "description": "Opaque bounded fabric-local channel identity.",
            "type": "string",
            "pattern": "^channel-[0-9a-f]{16}$"
          },
          "leftTransport": {
            "description": "Connecting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "rightTransport": {
            "description": "Accepting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "queuedPacketsLeft": {
            "description": "Packets queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesLeft": {
            "description": "Bytes queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedPacketsRight": {
            "description": "Packets queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesRight": {
            "description": "Bytes queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Close is initiated or one endpoint is terminal.",
            "const": "Closing"
          },
          "leftTerminal": {
            "description": "Connecting endpoint terminal, when committed.",
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-terminal"
          },
          "rightTerminal": {
            "description": "Accepting endpoint terminal, when committed.",
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-terminal"
          }
        },
        "required": [
          "channelId",
          "leftTransport",
          "rightTransport",
          "state",
          "queuedPacketsLeft",
          "queuedBytesLeft",
          "queuedPacketsRight",
          "queuedBytesRight"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "channelId": {
            "description": "Opaque bounded fabric-local channel identity.",
            "type": "string",
            "pattern": "^channel-[0-9a-f]{16}$"
          },
          "leftTransport": {
            "description": "Connecting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "rightTransport": {
            "description": "Accepting transport, fixed at commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:transport-name"
          },
          "queuedPacketsLeft": {
            "description": "Packets queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesLeft": {
            "description": "Bytes queued for the connecting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedPacketsRight": {
            "description": "Packets queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "queuedBytesRight": {
            "description": "Bytes queued for the accepting endpoint.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Both endpoint terminals are committed.",
            "const": "Terminal"
          },
          "leftTerminal": {
            "description": "Connecting endpoint terminal.",
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-terminal"
          },
          "rightTerminal": {
            "description": "Accepting endpoint terminal.",
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-terminal"
          }
        },
        "required": [
          "channelId",
          "leftTransport",
          "rightTransport",
          "queuedPacketsLeft",
          "queuedBytesLeft",
          "queuedPacketsRight",
          "queuedBytesRight",
          "state",
          "leftTerminal",
          "rightTerminal"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot",
    "title": "AGP Loopback counters-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "CountersSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign counters-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "connectionsAccepted": {
        "description": "Monotonic connectionsAccepted counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "connectionsRejected": {
        "description": "Monotonic connectionsRejected counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "packetsAcceptedLeftToRight": {
        "description": "Monotonic packetsAcceptedLeftToRight counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "bytesAcceptedLeftToRight": {
        "description": "Monotonic bytesAcceptedLeftToRight counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "packetsAcceptedRightToLeft": {
        "description": "Monotonic packetsAcceptedRightToLeft counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "bytesAcceptedRightToLeft": {
        "description": "Monotonic bytesAcceptedRightToLeft counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "backpressureActivations": {
        "description": "Monotonic backpressureActivations counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "gracefulChannelCloses": {
        "description": "Monotonic gracefulChannelCloses counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "forcedChannelAborts": {
        "description": "Monotonic forcedChannelAborts counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      },
      "adapterInvariantFaults": {
        "description": "Monotonic adapterInvariantFaults counter.",
        "$ref": "urn:agp:schema:v1:transport-loopback:common:counter-value"
      }
    },
    "required": [
      "connectionsAccepted",
      "connectionsRejected",
      "packetsAcceptedLeftToRight",
      "bytesAcceptedLeftToRight",
      "packetsAcceptedRightToLeft",
      "bytesAcceptedRightToLeft",
      "backpressureActivations",
      "gracefulChannelCloses",
      "forcedChannelAborts",
      "adapterInvariantFaults"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:fabric-failure-snapshot",
    "title": "AGP Loopback fabric-failure-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "FabricFailureSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign fabric-failure-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-ADAPTER-INVARIANT-FAILURE-1",
        "LOOPBACK-MONOTONIC-EXHAUSTION-1"
      ]
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "code": {
            "description": "Terminal adapter-invariant failure code.",
            "const": "ADAPTER_FAULT"
          }
        },
        "required": [
          "code"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "code": {
            "description": "Terminal monotonic-domain failure code.",
            "const": "MONOTONIC_DOMAIN_EXHAUSTED"
          },
          "domain": {
            "description": "Exhausted revision or arbitration domain.",
            "type": "string",
            "enum": [
              "revision",
              "arbitration-sequence"
            ]
          }
        },
        "required": [
          "code",
          "domain"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "code": {
            "description": "Terminal monotonic-domain failure code.",
            "const": "MONOTONIC_DOMAIN_EXHAUSTED"
          },
          "domain": {
            "description": "Counter-domain discriminator.",
            "const": "counter"
          },
          "counterKey": {
            "description": "Exact counter whose delta could not commit.",
            "$ref": "urn:agp:schema:v1:transport-loopback:codes:counter-key"
          }
        },
        "required": [
          "code",
          "domain",
          "counterKey"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:fabric-snapshot",
    "title": "AGP Loopback fabric-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "FabricSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign fabric-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "fabricId": {
            "description": "Display identity of this explicit fabric.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
          },
          "revision": {
            "description": "Canonical visible-state revision.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-revision"
          },
          "listeners": {
            "description": "Deterministically ordered bounded listener rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot"
            }
          },
          "channels": {
            "description": "Deterministically ordered bounded channel rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot"
            }
          },
          "resources": {
            "description": "Current finite resource gauges.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot"
          },
          "counters": {
            "description": "Closed monotonic counter catalog.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot"
          },
          "state": {
            "description": "Fabric lifecycle state Running.",
            "const": "Running"
          }
        },
        "required": [
          "fabricId",
          "revision",
          "listeners",
          "channels",
          "resources",
          "counters",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "fabricId": {
            "description": "Display identity of this explicit fabric.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
          },
          "revision": {
            "description": "Canonical visible-state revision.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-revision"
          },
          "listeners": {
            "description": "Deterministically ordered bounded listener rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot"
            }
          },
          "channels": {
            "description": "Deterministically ordered bounded channel rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot"
            }
          },
          "resources": {
            "description": "Current finite resource gauges.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot"
          },
          "counters": {
            "description": "Closed monotonic counter catalog.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot"
          },
          "state": {
            "description": "Fabric lifecycle state Closing.",
            "const": "Closing"
          }
        },
        "required": [
          "fabricId",
          "revision",
          "listeners",
          "channels",
          "resources",
          "counters",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "fabricId": {
            "description": "Display identity of this explicit fabric.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
          },
          "revision": {
            "description": "Canonical visible-state revision.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-revision"
          },
          "listeners": {
            "description": "Deterministically ordered bounded listener rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot"
            }
          },
          "channels": {
            "description": "Deterministically ordered bounded channel rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot"
            }
          },
          "resources": {
            "description": "Current finite resource gauges.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot"
          },
          "counters": {
            "description": "Closed monotonic counter catalog.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot"
          },
          "state": {
            "description": "Fabric lifecycle state Closed.",
            "const": "Closed"
          }
        },
        "required": [
          "fabricId",
          "revision",
          "listeners",
          "channels",
          "resources",
          "counters",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "fabricId": {
            "description": "Display identity of this explicit fabric.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-id"
          },
          "revision": {
            "description": "Canonical visible-state revision.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:fabric-revision"
          },
          "listeners": {
            "description": "Deterministically ordered bounded listener rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot"
            }
          },
          "channels": {
            "description": "Deterministically ordered bounded channel rows.",
            "type": "array",
            "maxItems": 4096,
            "items": {
              "$ref": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot"
            }
          },
          "resources": {
            "description": "Current finite resource gauges.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot"
          },
          "counters": {
            "description": "Closed monotonic counter catalog.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot"
          },
          "state": {
            "description": "Terminal failed fabric state.",
            "const": "Failed"
          },
          "failure": {
            "description": "Exact terminal fabric failure.",
            "$ref": "urn:agp:schema:v1:transport-loopback:operations:fabric-failure-snapshot"
          }
        },
        "required": [
          "fabricId",
          "revision",
          "listeners",
          "channels",
          "resources",
          "counters",
          "state",
          "failure"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot",
    "title": "AGP Loopback listener-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "ListenerSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign listener-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": [
        "LOOPBACK-SNAPSHOT-RETENTION-1"
      ]
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "listenerId": {
            "description": "Opaque bounded fabric-local listener identity.",
            "type": "string",
            "pattern": "^listener-[0-9a-f]{16}$"
          },
          "address": {
            "description": "Exact registered address.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:loopback-address"
          },
          "activeChannels": {
            "description": "Physically retained accepted channels.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Live listener state.",
            "const": "Listening"
          }
        },
        "required": [
          "listenerId",
          "address",
          "activeChannels",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "listenerId": {
            "description": "Opaque bounded fabric-local listener identity.",
            "type": "string",
            "pattern": "^listener-[0-9a-f]{16}$"
          },
          "address": {
            "description": "Exact registered address.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:loopback-address"
          },
          "activeChannels": {
            "description": "Physically retained accepted channels.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Listener close has begun.",
            "const": "Closing"
          }
        },
        "required": [
          "listenerId",
          "address",
          "activeChannels",
          "state"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "listenerId": {
            "description": "Opaque bounded fabric-local listener identity.",
            "type": "string",
            "pattern": "^listener-[0-9a-f]{16}$"
          },
          "address": {
            "description": "Exact registered address.",
            "$ref": "urn:agp:schema:v1:transport-loopback:common:loopback-address"
          },
          "activeChannels": {
            "description": "Physically retained accepted channels.",
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "state": {
            "description": "Listener terminal is committed.",
            "const": "Terminal"
          },
          "terminal": {
            "description": "Exact neutral listener terminal.",
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-listener-terminal"
          }
        },
        "required": [
          "listenerId",
          "address",
          "activeChannels",
          "state",
          "terminal"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot",
    "title": "AGP Loopback resources-snapshot",
    "x-agp": {
      "owner": "@agp/transport-loopback",
      "typescript": "ResourcesSnapshot",
      "kind": "operations",
      "mechanics": "Sovereign resources-snapshot data contract owned by @agp/transport-loopback.",
      "rationale": "One closed record keeps production Loopback configuration and state independently inspectable.",
      "consequence": "Accepting another shape would make fabric capacity, lifecycle, or terminal evidence ambiguous.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "pendingAcquisitions": {
        "description": "Current uncommitted acquisitions.",
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "activeChannels": {
        "description": "Current physically retained logical channels.",
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "pendingSendBytes": {
        "description": "Copied bytes waiting for queue admission.",
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "queuedPackets": {
        "description": "Packets accepted into all ingress queues.",
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      },
      "queuedBytes": {
        "description": "Bytes accepted into all ingress queues.",
        "type": "integer",
        "minimum": 0,
        "maximum": 9007199254740991
      }
    },
    "required": [
      "pendingAcquisitions",
      "activeChannels",
      "pendingSendBytes",
      "queuedPackets",
      "queuedBytes"
    ],
    "additionalProperties": false
  }
] as const);

export const loopbackSchemaCatalogV1 = Object.freeze({
  "schemaVersion": "agp.schema-catalog/v1",
  "owner": "@agp/transport-loopback",
  "schemas": [
    {
      "id": "urn:agp:schema:v1:transport-loopback:codes:counter-key",
      "path": "codes/counter-key.schema.json",
      "typescript": "CounterKey",
      "sha256": "c399b281c306abdf2a3311ea6f0aaf500e51dbcc6da6bc6f8848de1b3cb103cf"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:codes:fabric-failure-code",
      "path": "codes/fabric-failure-code.schema.json",
      "typescript": "FabricFailureCode",
      "sha256": "b266efac76c22cfa4ff64909a2a91476fb95e3f167c528120c1f8afd27c22c03"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:codes:monotonic-domain",
      "path": "codes/monotonic-domain.schema.json",
      "typescript": "MonotonicDomain",
      "sha256": "ca96cc62b611990ea9ed27aa3268c68c7a3fb251259cb7f94d505a0cfc2b8f4a"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:common:counter-value",
      "path": "common/counter-value.schema.json",
      "typescript": "CounterValue",
      "sha256": "ffe132a82672284fff820292de28136fc2acd2c6a0cb6d8a2e123a10df3adfdf"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:common:fabric-id",
      "path": "common/fabric-id.schema.json",
      "typescript": "FabricId",
      "sha256": "45aa2f34d1ae4fd79e0fbdeb4155221f23ce70ee1b2d4c5d2d6ab9d9b3d8b109"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:common:fabric-revision",
      "path": "common/fabric-revision.schema.json",
      "typescript": "FabricRevision",
      "sha256": "354c867b2fd4911b4beef325d6b5f0bea3cca93024c1834c1ed9363037a4e87a"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:common:loopback-address",
      "path": "common/loopback-address.schema.json",
      "typescript": "LoopbackAddress",
      "sha256": "fba5eddbe2e6b08a90e501a9a1da60500de62c92d21e8080ded6c610d0410eee"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:common:transport-name",
      "path": "common/transport-name.schema.json",
      "typescript": "TransportName",
      "sha256": "71b305e14b53cc79bc233a063d88ca80f91aab49595a6527383006cada38b539"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:configuration:fabric",
      "path": "configuration/fabric.schema.json",
      "typescript": "Fabric",
      "sha256": "1f342fd079c8885b40f34fb575363da5324e4ae29d291ab2202933b224b8361d"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:configuration:limits",
      "path": "configuration/limits.schema.json",
      "typescript": "Limits",
      "sha256": "ef6c5c95df06c852ed23a2d57a7b843c83df5e44933d3807375b943e3531cd8f"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:configuration:listener",
      "path": "configuration/listener.schema.json",
      "typescript": "Listener",
      "sha256": "80b01fcf85f287d282845a8d3c7b4360fbe3ee60409d32956881ca72b0e78b9b"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:configuration:target",
      "path": "configuration/target.schema.json",
      "typescript": "Target",
      "sha256": "d840640f6b359c64d3dd7a43c69d3d65ed39be787359950eedc3d2685a5856f4"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:configuration:transport",
      "path": "configuration/transport.schema.json",
      "typescript": "Transport",
      "sha256": "f96dfce49b3322bad482764b1d944ba370154b2b4184106272a788c40a9557ec"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:channel-snapshot",
      "path": "operations/channel-snapshot.schema.json",
      "typescript": "ChannelSnapshot",
      "sha256": "deb9b3ad84e954c04b0e013b278abb4f7d9a546af692a3067a0ac533f917eaf8"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:counters-snapshot",
      "path": "operations/counters-snapshot.schema.json",
      "typescript": "CountersSnapshot",
      "sha256": "da83d953cf28fe2e3160d3723c897045b5ceea826af096df948728cc133f8be1"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:fabric-failure-snapshot",
      "path": "operations/fabric-failure-snapshot.schema.json",
      "typescript": "FabricFailureSnapshot",
      "sha256": "fa03fb252e2ae8d9b198f1745d8dc00f3ba8e828e7c90f5ccda2e7407f77299d"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:fabric-snapshot",
      "path": "operations/fabric-snapshot.schema.json",
      "typescript": "FabricSnapshot",
      "sha256": "fa0011d0cac42998137e13bbd0b7669ffdf98204a59dd17140d10750276173ba"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:listener-snapshot",
      "path": "operations/listener-snapshot.schema.json",
      "typescript": "ListenerSnapshot",
      "sha256": "28e72c0df6a6816a2f5e69ef0726bca6f54252f3996629f6d8b997c47d387e61"
    },
    {
      "id": "urn:agp:schema:v1:transport-loopback:operations:resources-snapshot",
      "path": "operations/resources-snapshot.schema.json",
      "typescript": "ResourcesSnapshot",
      "sha256": "64da01880f44d95ff9b99425b268af895db59fa9bd83e3dfde4f1f4070f4d976"
    }
  ]
} as const);

export const LOOPBACK_V1_SCHEMA_IDS = Object.freeze(loopbackSchemaCatalogV1.schemas.map((entry) => entry.id));
