// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
import type {
  TransportListenerTerminal,
  TransportTerminal,
} from "@agp/transport";

export type LoopbackFabricId = string;
export type LoopbackAddress = string;
export type LoopbackTransportName = string;
export type LoopbackFabricRevision = string;
export type LoopbackCounterValue = string;
export type LoopbackCounterKey =
  | "connectionsAccepted"
  | "connectionsRejected"
  | "packetsAcceptedLeftToRight"
  | "bytesAcceptedLeftToRight"
  | "packetsAcceptedRightToLeft"
  | "bytesAcceptedRightToLeft"
  | "backpressureActivations"
  | "gracefulChannelCloses"
  | "forcedChannelAborts"
  | "adapterInvariantFaults";

export interface LoopbackFabricLimits {
  readonly maxTransports: number;
  readonly maxListeners: number;
  readonly maxPendingAcquisitions: number;
  readonly maxActiveChannels: number;
  readonly maxPacketBytes: number;
  readonly maxBufferedPacketsPerChannel: number;
  readonly maxBufferedBytesPerChannel: number;
  readonly maxQueuedPacketsTotal: number;
  readonly maxQueuedBytesTotal: number;
  readonly maxPendingSendBytesTotal: number;
}

export interface LoopbackFabricConfig {
  readonly fabricId: LoopbackFabricId;
  readonly limits: LoopbackFabricLimits;
}

export interface LoopbackTransportConfig {
  readonly transportName: LoopbackTransportName;
  readonly capabilities: {
    readonly listen: boolean;
    readonly connect: boolean;
  };
}

export interface LoopbackListenerConfig {
  readonly fabricId: LoopbackFabricId;
  readonly address: LoopbackAddress;
}

export interface LoopbackTargetConfig {
  readonly fabricId: LoopbackFabricId;
  readonly address: LoopbackAddress;
}

export type LoopbackFabricFailureSnapshot =
  | {
      readonly code: "ADAPTER_FAULT";
    }
  | {
      readonly code: "MONOTONIC_DOMAIN_EXHAUSTED";
      readonly domain: "revision" | "arbitration-sequence";
    }
  | {
      readonly code: "MONOTONIC_DOMAIN_EXHAUSTED";
      readonly domain: "counter";
      readonly counterKey: LoopbackCounterKey;
    };

export interface LoopbackListenerSnapshot {
  readonly listenerId: string;
  readonly address: LoopbackAddress;
  readonly state: "Listening" | "Closing" | "Terminal";
  readonly terminal?: TransportListenerTerminal;
  readonly activeChannels: number;
}

export interface LoopbackChannelSnapshot {
  readonly channelId: string;
  readonly leftTransport: LoopbackTransportName;
  readonly rightTransport: LoopbackTransportName;
  readonly state: "Open" | "Closing" | "Terminal";
  readonly leftTerminal?: TransportTerminal;
  readonly rightTerminal?: TransportTerminal;
  readonly queuedPacketsLeft: number;
  readonly queuedBytesLeft: number;
  readonly queuedPacketsRight: number;
  readonly queuedBytesRight: number;
}

export interface LoopbackResourcesSnapshot {
  readonly pendingAcquisitions: number;
  readonly activeChannels: number;
  readonly pendingSendBytes: number;
  readonly queuedPackets: number;
  readonly queuedBytes: number;
}

export interface LoopbackCountersSnapshot {
  readonly connectionsAccepted: LoopbackCounterValue;
  readonly connectionsRejected: LoopbackCounterValue;
  readonly packetsAcceptedLeftToRight: LoopbackCounterValue;
  readonly bytesAcceptedLeftToRight: LoopbackCounterValue;
  readonly packetsAcceptedRightToLeft: LoopbackCounterValue;
  readonly bytesAcceptedRightToLeft: LoopbackCounterValue;
  readonly backpressureActivations: LoopbackCounterValue;
  readonly gracefulChannelCloses: LoopbackCounterValue;
  readonly forcedChannelAborts: LoopbackCounterValue;
  readonly adapterInvariantFaults: LoopbackCounterValue;
}

export type LoopbackFabricSnapshot =
  | {
      readonly fabricId: LoopbackFabricId;
      readonly state: "Running" | "Closing" | "Closed";
      readonly revision: LoopbackFabricRevision;
      readonly listeners: readonly LoopbackListenerSnapshot[];
      readonly channels: readonly LoopbackChannelSnapshot[];
      readonly resources: LoopbackResourcesSnapshot;
      readonly counters: LoopbackCountersSnapshot;
    }
  | {
      readonly fabricId: LoopbackFabricId;
      readonly state: "Failed";
      readonly revision: LoopbackFabricRevision;
      readonly failure: LoopbackFabricFailureSnapshot;
      readonly listeners: readonly LoopbackListenerSnapshot[];
      readonly channels: readonly LoopbackChannelSnapshot[];
      readonly resources: LoopbackResourcesSnapshot;
      readonly counters: LoopbackCountersSnapshot;
    };
