// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
export const transportSchemaDocumentsV1 = Object.freeze([
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:channel-security-keying",
    "title": "ChannelSecurityKeying",
    "description": "Closed channel-security-keying code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "ChannelSecurityKeying",
      "kind": "code",
      "mechanics": "Defines the bounded channel-security-keying value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "network",
      "node"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-input-rejection-code",
    "title": "TransportInputRejectionCode",
    "description": "Closed transport-input-rejection-code code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportInputRejectionCode",
      "kind": "code",
      "mechanics": "Defines the bounded transport-input-rejection-code value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "PACKET_TOO_LARGE",
      "MALFORMED_CARRIER_INPUT"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-listener-terminal-kind",
    "title": "TransportListenerTerminalKind",
    "description": "Closed transport-listener-terminal-kind code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportListenerTerminalKind",
      "kind": "code",
      "mechanics": "Defines the bounded transport-listener-terminal-kind value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "graceful",
      "aborted",
      "io-failure",
      "resource-exhausted",
      "adapter-fault"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-operation-error-code",
    "title": "TransportOperationErrorCode",
    "description": "Closed transport-operation-error-code code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportOperationErrorCode",
      "kind": "code",
      "mechanics": "Defines the bounded transport-operation-error-code value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "REFERENCE_INVALID",
      "BINDING_UNAVAILABLE",
      "LISTEN_FAILED",
      "CONNECT_FAILED",
      "CAPACITY_EXCEEDED",
      "PACKET_TOO_LARGE",
      "CONCURRENT_OPERATION",
      "CHANNEL_TERMINAL",
      "OPERATION_ABORTED",
      "SEND_FAILED",
      "ADAPTER_FAULT"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-operation-phase",
    "title": "TransportOperationPhase",
    "description": "Closed transport-operation-phase code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportOperationPhase",
      "kind": "code",
      "mechanics": "Defines the bounded transport-operation-phase value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "resolve-listener",
      "resolve-target",
      "listen",
      "connect",
      "send",
      "read",
      "close",
      "wait-terminal"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-terminal-kind",
    "title": "TransportTerminalKind",
    "description": "Closed transport-terminal-kind code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportTerminalKind",
      "kind": "code",
      "mechanics": "Defines the bounded transport-terminal-kind value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "graceful",
      "aborted",
      "io-failure",
      "resource-exhausted",
      "binding-violation",
      "adapter-fault"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:codes:transport-terminal-origin",
    "title": "TransportTerminalOrigin",
    "description": "Closed transport-terminal-origin code domain.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportTerminalOrigin",
      "kind": "code",
      "mechanics": "Defines the bounded transport-terminal-origin value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "enum": [
      "local",
      "remote",
      "carrier"
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:common:secret-identity",
    "title": "SecretIdentity",
    "description": "Label a peer presents to select which pre-shared secret authenticates it.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "SecretIdentity",
      "kind": "scalar",
      "mechanics": "Defines the bounded secret-identity value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "minLength": 1,
    "maxLength": 256,
    "pattern": "^[^\\u0000-\\u001F\\u007F]+$"
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:common:transport-ref",
    "title": "TransportRef",
    "description": "Application-local logical name resolving to one bound acquisition capability.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportRef",
      "kind": "scalar",
      "mechanics": "Defines the bounded transport-ref value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "string",
    "minLength": 1,
    "maxLength": 64,
    "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$"
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:channel-security-profile",
    "title": "ChannelSecurityProfile",
    "description": "Declared channel protection, without any secret value.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "ChannelSecurityProfile",
      "kind": "contract",
      "mechanics": "Defines the bounded channel-security-profile value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "mode": {
            "const": "unprotected",
            "description": "No confidentiality or peer authentication."
          }
        },
        "required": [
          "mode"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "mode": {
            "const": "preshared-key",
            "description": "Pre-shared-secret discriminator."
          },
          "keying": {
            "$ref": "urn:agp:schema:v1:transport:codes:channel-security-keying",
            "description": "Whether one secret covers the topology or one covers each identity."
          }
        },
        "required": [
          "mode",
          "keying"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-abort-intent",
    "title": "TransportAbortIntent",
    "description": "Bounded neutral immediate-abort intent.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportAbortIntent",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-abort-intent value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "kind": {
        "type": "string",
        "enum": [
          "deadline",
          "capacity",
          "invariant",
          "forced-stop"
        ],
        "description": "Neutral abort classification."
      },
      "code": {
        "type": "string",
        "pattern": "^[A-Z][A-Z0-9_]{0,63}$",
        "description": "Stable bounded local diagnostic code."
      }
    },
    "required": [
      "kind",
      "code"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-acquisition-options",
    "title": "TransportAcquisitionOptions",
    "description": "Neutral options supplied to one bound connect capability.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportAcquisitionOptions",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-acquisition-options value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "channel": {
        "$ref": "urn:agp:schema:v1:transport:contracts:transport-channel-limits",
        "description": "Authoritative channel limits."
      }
    },
    "required": [
      "channel"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-channel-limits",
    "title": "TransportChannelLimits",
    "description": "Exact common packet and inbound-buffer bounds for one channel.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportChannelLimits",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-channel-limits value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": [
        "TRANSPORT-CHANNEL-ORDER-1"
      ]
    },
    "type": "object",
    "properties": {
      "maxPacketBytes": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991,
        "description": "Maximum bytes in one decoded packet."
      },
      "maxBufferedPackets": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991,
        "description": "Maximum complete inbound packets retained."
      },
      "maxBufferedBytes": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991,
        "description": "Maximum aggregate inbound packet bytes retained."
      }
    },
    "required": [
      "maxPacketBytes",
      "maxBufferedPackets",
      "maxBufferedBytes"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-close-intent",
    "title": "TransportCloseIntent",
    "description": "Bounded neutral graceful-close intent.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportCloseIntent",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-close-intent value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "kind": {
        "type": "string",
        "enum": [
          "normal",
          "node-stop",
          "session-replaced",
          "protocol-fatal"
        ],
        "description": "Neutral close classification."
      },
      "code": {
        "type": "string",
        "pattern": "^[A-Z][A-Z0-9_]{0,63}$",
        "description": "Stable bounded local diagnostic code."
      }
    },
    "required": [
      "kind",
      "code"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
    "title": "TransportDiagnostic",
    "description": "Bounded sanitized adapter diagnostic safe at the neutral boundary.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportDiagnostic",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-diagnostic value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "code": {
        "type": "string",
        "pattern": "^[A-Z][A-Z0-9_]{0,63}$",
        "description": "Stable diagnostic code."
      },
      "message": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[^\\u0000-\\u001F\\u007F]+$",
        "description": "Optional sanitized diagnostic text."
      }
    },
    "required": [
      "code"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-input-rejected",
    "title": "TransportInputRejected",
    "description": "Ordered evidence that one carrier record could not form a common packet.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportInputRejected",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-input-rejected value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "kind": {
        "const": "input-rejected",
        "description": "Read-result discriminator."
      },
      "code": {
        "$ref": "urn:agp:schema:v1:transport:codes:transport-input-rejection-code",
        "description": "Stable rejection classification."
      }
    },
    "required": [
      "kind",
      "code"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-listen-options",
    "title": "TransportListenOptions",
    "description": "Neutral options supplied to one bound listen capability.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportListenOptions",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-listen-options value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "limits": {
        "$ref": "urn:agp:schema:v1:transport:contracts:transport-listener-limits",
        "description": "Authoritative listener limits."
      }
    },
    "required": [
      "limits"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-listener-limits",
    "title": "TransportListenerLimits",
    "description": "Exact acquisition and channel bounds for one listener.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportListenerLimits",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-listener-limits value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "maxPendingAcquisitions": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991,
        "description": "Maximum carrier acquisitions awaiting disposition."
      },
      "maxActiveChannels": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991,
        "description": "Maximum physically retained accepted channels."
      },
      "channel": {
        "$ref": "urn:agp:schema:v1:transport:contracts:transport-channel-limits",
        "description": "Limits applied to each accepted channel."
      }
    },
    "required": [
      "maxPendingAcquisitions",
      "maxActiveChannels",
      "channel"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-listener-publication",
    "title": "TransportListenerPublication",
    "description": "Sanitized operator evidence returned by one listener.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportListenerPublication",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-listener-publication value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "displayAddress": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[^\\u0000-\\u001F\\u007F]+$",
        "description": "Optional non-authoritative display address."
      }
    },
    "required": [],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-listener-terminal",
    "title": "TransportListenerTerminal",
    "description": "One immutable listener terminal with legal origin/kind products only.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportListenerTerminal",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-listener-terminal value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "origin": {
            "const": "local",
            "description": "Terminal authority origin."
          },
          "kind": {
            "type": "string",
            "enum": [
              "graceful",
              "aborted"
            ],
            "description": "Terminal classification."
          },
          "diagnostic": {
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
            "description": "Optional bounded diagnostic."
          }
        },
        "required": [
          "origin",
          "kind"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "origin": {
            "const": "carrier",
            "description": "Terminal authority origin."
          },
          "kind": {
            "type": "string",
            "enum": [
              "io-failure",
              "resource-exhausted",
              "adapter-fault"
            ],
            "description": "Terminal classification."
          },
          "diagnostic": {
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
            "description": "Optional bounded diagnostic."
          }
        },
        "required": [
          "origin",
          "kind"
        ],
        "additionalProperties": false
      }
    ]
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-peer-evidence",
    "title": "TransportPeerEvidence",
    "description": "Closed immutable facts established during channel acquisition.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportPeerEvidence",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-peer-evidence value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": []
    },
    "type": "object",
    "properties": {
      "locality": {
        "type": "string",
        "enum": [
          "process-local",
          "network"
        ],
        "description": "Observed carrier locality."
      },
      "protection": {
        "type": "string",
        "enum": [
          "none",
          "integrity",
          "confidentiality-and-integrity"
        ],
        "description": "Observed carrier protection."
      },
      "authentication": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "kind": {
                "const": "none",
                "description": "No authenticated principal."
              }
            },
            "required": [
              "kind"
            ],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "kind": {
                "const": "verified",
                "description": "Verified-principal discriminator."
              },
              "principal": {
                "type": "string",
                "minLength": 1,
                "maxLength": 256,
                "pattern": "^[^\\u0000-\\u001F\\u007F]+$",
                "description": "Bounded verified deployment principal."
              },
              "method": {
                "type": "string",
                "pattern": "^[a-z][a-z0-9._-]{0,63}$",
                "description": "Stable verification method."
              }
            },
            "required": [
              "kind",
              "principal",
              "method"
            ],
            "additionalProperties": false
          }
        ],
        "description": "Observed authentication evidence."
      }
    },
    "required": [
      "locality",
      "protection",
      "authentication"
    ],
    "additionalProperties": false
  },
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "urn:agp:schema:v1:transport:contracts:transport-terminal",
    "title": "TransportTerminal",
    "description": "One immutable channel terminal with legal origin/kind products only.",
    "x-agp": {
      "owner": "@agp/transport",
      "typescript": "TransportTerminal",
      "kind": "contract",
      "mechanics": "Defines the bounded transport-terminal value crossing the neutral transport boundary.",
      "rationale": "One schema and generated type prevent adapter-specific reinterpretation.",
      "consequence": "A divergent shape makes transport implementations observably incompatible.",
      "semanticRules": [
        "TRANSPORT-TERMINAL-ONCE-1"
      ]
    },
    "oneOf": [
      {
        "type": "object",
        "properties": {
          "origin": {
            "const": "local",
            "description": "Terminal authority origin."
          },
          "kind": {
            "type": "string",
            "enum": [
              "graceful",
              "aborted",
              "resource-exhausted"
            ],
            "description": "Terminal classification."
          },
          "diagnostic": {
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
            "description": "Optional bounded diagnostic."
          }
        },
        "required": [
          "origin",
          "kind"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "origin": {
            "const": "remote",
            "description": "Terminal authority origin."
          },
          "kind": {
            "type": "string",
            "enum": [
              "graceful",
              "io-failure",
              "binding-violation"
            ],
            "description": "Terminal classification."
          },
          "diagnostic": {
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
            "description": "Optional bounded diagnostic."
          }
        },
        "required": [
          "origin",
          "kind"
        ],
        "additionalProperties": false
      },
      {
        "type": "object",
        "properties": {
          "origin": {
            "const": "carrier",
            "description": "Terminal authority origin."
          },
          "kind": {
            "type": "string",
            "enum": [
              "io-failure",
              "resource-exhausted",
              "binding-violation",
              "adapter-fault"
            ],
            "description": "Terminal classification."
          },
          "diagnostic": {
            "$ref": "urn:agp:schema:v1:transport:contracts:transport-diagnostic",
            "description": "Optional bounded diagnostic."
          }
        },
        "required": [
          "origin",
          "kind"
        ],
        "additionalProperties": false
      }
    ]
  }
]) as readonly Readonly<Record<string, unknown>>[];
