// Generated by scripts/generate-contracts.mjs. DO NOT EDIT.
export type TransportRef = string;
export type SecretIdentity = string;
export type TransportTerminalOrigin = "local" | "remote" | "carrier";
export type TransportTerminalKind = "graceful" | "aborted" | "io-failure" | "resource-exhausted" | "binding-violation" | "adapter-fault";
export type TransportListenerTerminalKind = "graceful" | "aborted" | "io-failure" | "resource-exhausted" | "adapter-fault";
export type TransportInputRejectionCode = "PACKET_TOO_LARGE" | "MALFORMED_CARRIER_INPUT";
export type TransportOperationErrorCode = "REFERENCE_INVALID" | "BINDING_UNAVAILABLE" | "LISTEN_FAILED" | "CONNECT_FAILED" | "CAPACITY_EXCEEDED" | "PACKET_TOO_LARGE" | "CONCURRENT_OPERATION" | "CHANNEL_TERMINAL" | "OPERATION_ABORTED" | "SEND_FAILED" | "ADAPTER_FAULT";
export type ChannelSecurityKeying = "network" | "node";
export type TransportOperationPhase = "resolve-listener" | "resolve-target" | "listen" | "connect" | "send" | "read" | "close" | "wait-terminal";
export type ChannelSecurityProfile =
  | { readonly mode: "unprotected" }
  | { readonly mode: "preshared-key"; readonly keying: ChannelSecurityKeying };
export interface TransportChannelLimits {
  readonly maxPacketBytes: number;
  readonly maxBufferedPackets: number;
  readonly maxBufferedBytes: number;
}
export interface TransportListenerLimits {
  readonly maxPendingAcquisitions: number;
  readonly maxActiveChannels: number;
  readonly channel: TransportChannelLimits;
}
export interface TransportListenOptions {
  readonly limits: TransportListenerLimits;
}
export interface TransportAcquisitionOptions {
  readonly channel: TransportChannelLimits;
}
export interface TransportInputRejected {
  readonly kind: "input-rejected";
  readonly code: TransportInputRejectionCode;
}
export interface TransportDiagnostic {
  readonly code: string;
  readonly message?: string;
}
export type TransportPeerEvidence = Readonly<{
  locality: "process-local" | "network";
  protection: "none" | "integrity" | "confidentiality-and-integrity";
  authentication:
    | Readonly<{ kind: "none" }>
    | Readonly<{ kind: "verified"; principal: string; method: string }>;
}>;
export type TransportTerminal =
  | Readonly<{ origin: "local"; kind: "graceful" | "aborted" | "resource-exhausted"; diagnostic?: TransportDiagnostic }>
  | Readonly<{ origin: "remote"; kind: "graceful" | "io-failure" | "binding-violation"; diagnostic?: TransportDiagnostic }>
  | Readonly<{ origin: "carrier"; kind: "io-failure" | "resource-exhausted" | "binding-violation" | "adapter-fault"; diagnostic?: TransportDiagnostic }>;
export type TransportListenerTerminal =
  | Readonly<{ origin: "local"; kind: "graceful" | "aborted"; diagnostic?: TransportDiagnostic }>
  | Readonly<{ origin: "carrier"; kind: "io-failure" | "resource-exhausted" | "adapter-fault"; diagnostic?: TransportDiagnostic }>;
export interface TransportCloseIntent {
  readonly kind: "normal" | "node-stop" | "session-replaced" | "protocol-fatal";
  readonly code: string;
}
export interface TransportAbortIntent {
  readonly kind: "deadline" | "capacity" | "invariant" | "forced-stop";
  readonly code: string;
}
export interface TransportListenerPublication {
  readonly displayAddress?: string;
}
